# -*- coding: utf-8 -*-
"""student_management_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QLI1PRvd21xFrq4nSSp2wZXP9vilPVTs
"""

students = []

while True:
    print("\nSTUDENT MANAGEMENT SYSTEM")
    print("1. Add Student")
    print("2. View Students")
    print("3. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        name = input("Enter student name: ")
        roll = input("Enter roll number: ")
        students.append([name, roll])
        print("Student added successfully")

    elif choice == "2":
        if not students:
            print("No students found")
        else:
            print("\nStudent List:")
            for s in students:
                print("Name:", s[0], "| Roll:", s[1])

    elif choice == "3":
        print("Exiting program")
        break

    else:
        print("Invalid choice. Try again.")